version: '2'
services:
  # MySQL Database
  mysqldb:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stationSki
    ports:
      - "3306:3306"
    volumes:
      - dockerAngularSpringDatabaseData:/var/lib/mysql
    networks:
      - back

  # Spring Boot Backend
  spring-backend:
    build:
      context: ./
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb
    networks:
      - back
volumes:
  dockerAngularSpringDatabaseData:

networks:
  back:

